import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import fg from 'fast-glob'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SRC = path.join(ROOT, 'app/assets/fonts')
const OUT = path.join(ROOT, 'public/fonts')
const STYLES_OUT = path.join(ROOT, 'app/assets/styles/base/_fonts.generated.scss')
const CONFIG_PATH = path.join(ROOT, 'fonts.config.json')

async function readConfig() {
	try {
		const config = JSON.parse(await fs.readFile(CONFIG_PATH, 'utf8'))
		return {
			defaults: {
				display: config.defaults?.display || 'swap',
				varWght: config.defaults?.varWght || '300 700',
			},
			families: config.families || {},
			subsets: config.subsets || {},
		}
	} catch {
		return { defaults: { display: 'swap', varWght: '300 700' }, families: {}, subsets: {} }
	}
}

function tokens(fileName) {
	return fileName
		.replace(/\.woff2?$/i, '')
		.replace(/\[.*?]/g, '')
		.replace(/([a-z])([A-Z])/g, '$1 $2')
		.replace(/[_-]+/g, ' ')
		.toLowerCase()
		.split(/\s+/)
		.filter(Boolean)
}

function guessWeight(fileName) {
	const values = tokens(fileName)
	const has = (value) => values.includes(value)

	if (has('thin')) return 100
	if (has('extralight') || has('ultralight') || (has('extra') && has('light'))) return 200
	if (has('light')) return 300
	if (has('book')) return 350
	if (has('medium')) return 500
	if (has('semibold') || has('demibold') || (has('semi') && has('bold'))) return 600
	if (has('extrabold') || has('ultrabold') || (has('extra') && has('bold'))) return 800
	if (has('black') || has('heavy')) return 900
	if (has('bold')) return 700
	return 400
}

function isVariable(fileName) {
	const name = fileName.toLowerCase()
	return /\[.*wght.*]/.test(name) || /(?:variablefont|variable|[-_]vf)(?:[-_.]|$)/.test(name)
}

// Набор символов — последнее слово имени файла (Inter-Variable-cyrillic.woff2), диапазон — из
// subsets в fonts.config.json. Браузер качает только те файлы, символы которых есть на странице.
function subsetRange(fileName, subsets) {
	return subsets[tokens(fileName).at(-1)] || null
}

function isItalic(fileName) {
	return tokens(fileName).includes('italic')
}

// Путь от корня public без BASE: Vite сам добавляет base к таким адресам в CSS при сборке.
// Если зашивать BASE здесь, общий для dev и сборки _fonts.generated.scss после сборки
// с BASE ломал шрифты в запущенном dev-сервере.
function webPath(relativePath) {
	return `/fonts/${relativePath.split(path.sep).join('/')}`
}

async function copy(file, target) {
	await fs.mkdir(path.dirname(target), { recursive: true })
	await fs.copyFile(file, target)
}

function emitFace({ family, sourceWoff2, sourceWoff, style, weight, display, unicodeRange }) {
	const sources = [`url("${sourceWoff2}") format("woff2")`]
	if (sourceWoff) sources.push(`url("${sourceWoff}") format("woff")`)

	return [
		'@font-face {',
		`\tfont-family: "${family}";`,
		`\tsrc: ${sources.join(',\n\t\t')};`,
		`\tfont-weight: ${weight};`,
		`\tfont-style: ${style};`,
		`\tfont-display: ${display};`,
		...(unicodeRange ? [`\tunicode-range: ${unicodeRange};`] : []),
		'}',
	].join('\n')
}

async function writeStyles(content) {
	await fs.mkdir(path.dirname(STYLES_OUT), { recursive: true })
	await fs.writeFile(STYLES_OUT, `${content.trimEnd()}\n`)
}

const config = await readConfig()
const files = await fg('**/*.woff2', { cwd: SRC, absolute: true, caseSensitiveMatch: false })

await fs.rm(OUT, { recursive: true, force: true })

if (!files.length) {
	await writeStyles('/* AUTOGENERATED: no WOFF2 font sources found. */')
	console.log('Fonts: no WOFF2 sources, generated a CSS stub')
	process.exit(0)
}

const faces = []

for (const file of files.sort()) {
	const relativePath = path.relative(SRC, file)
	const relativeDir = path.dirname(relativePath)
	const folder =
		relativeDir === '.'
			? path.basename(file, path.extname(file)).split(/[-_]/)[0]
			: relativeDir.split(path.sep)[0]
	const family = config.families[folder]?.cssFamily || folder
	const fileName = path.basename(file)
	const style = isItalic(fileName) ? 'italic' : 'normal'
	const variable = isVariable(fileName)
	const targetWoff2 = path.join(OUT, relativePath)

	await copy(file, targetWoff2)

	const siblingWoff = file.replace(/\.woff2$/i, '.woff')
	let sourceWoff = null
	try {
		await fs.access(siblingWoff)
		const relativeWoff = relativePath.replace(/\.woff2$/i, '.woff')
		await copy(siblingWoff, path.join(OUT, relativeWoff))
		sourceWoff = webPath(relativeWoff)
	} catch {}

	const familyConfig = config.families[folder]
	const variableWeight =
		familyConfig?.[style]?.varWght || familyConfig?.normal?.varWght || config.defaults.varWght

	faces.push(
		emitFace({
			family,
			sourceWoff2: webPath(relativePath),
			sourceWoff,
			style,
			weight: variable ? variableWeight : guessWeight(fileName),
			display: config.defaults.display,
			unicodeRange: subsetRange(fileName, config.subsets),
		})
	)
}

await writeStyles(`/* AUTOGENERATED from app/assets/fonts. */\n\n${faces.join('\n\n')}`)
console.log(`Fonts: copied ${files.length} WOFF2 source(s) and generated @font-face CSS`)
